import os
import json
from typing import Dict, List, Tuple
import statistics as stats
from ultralytics import YOLO


def collect_val_metrics(weights_path: str, data_yaml_path: str, device: str | int = "cpu") -> Dict[str, float]:
    model = YOLO(weights_path)
    res = model.val(data=data_yaml_path, imgsz=640, device=device, project=os.path.abspath("output"), name="val-report", exist_ok=True)
    rd = getattr(res, "results_dict", None)
    return rd or {}


def collect_pretrained_metrics(data_yaml_path: str, device: str | int = "cpu") -> Dict[str, float]:
    try:
        model = YOLO("yolo11s.pt")
        model.names = ["strawberry"]
        res = model.val(data=data_yaml_path, imgsz=640, device=device, project=os.path.abspath("output"), name="val-pretrained", exist_ok=True)
        rd = getattr(res, "results_dict", None)
        return rd or {}
    except Exception:
        return {}


def list_images(dir_path: str) -> List[str]:
    exts = (".png", ".jpg", ".jpeg")
    return [os.path.join(dir_path, n) for n in sorted(os.listdir(dir_path)) if n.lower().endswith(exts)]


def read_gt_count(labels_dir: str, image_path: str) -> int:
    base = os.path.splitext(os.path.basename(image_path))[0]
    lbl_path = os.path.join(labels_dir, f"{base}.txt")
    if not os.path.exists(lbl_path):
        return 0
    with open(lbl_path, "r", encoding="utf-8") as f:
        return sum(1 for _ in f if _.strip())


def predict_count(model: YOLO, image_path: str, device: str | int = "cpu", conf: float = 0.5) -> int:
    r = model.predict(source=image_path, conf=conf, save=False, device=device)
    if not r:
        return 0
    b = getattr(r[0], "boxes", None)
    if b is None:
        return 0
    cls_ids = getattr(b, "cls", None)
    if cls_ids is None:
        return int(getattr(b, "shape", [0])[0])
    return int(cls_ids.shape[0])


def build_count_table(weights_path: str, images_dir: str, labels_dir: str, device: str | int = "cpu", max_rows: int = 10, conf: float = 0.5) -> List[Tuple[str, int, int, int]]:
    model = YOLO(weights_path)
    images = list_images(images_dir)[:max_rows]
    rows: List[Tuple[str, int, int, int]] = []
    for img_path in images:
        gt = read_gt_count(labels_dir, img_path)
        pr = predict_count(model, img_path, device=device, conf=conf)
        rows.append((os.path.basename(img_path), gt, pr, pr - gt))
    return rows


def compute_deltas(before: Dict[str, float], after: Dict[str, float]) -> Dict[str, float]:
    keys = [
        "metrics/precision(B)",
        "metrics/recall(B)",
        "metrics/mAP50(B)",
        "metrics/mAP50-95(B)",
        "fitness",
    ]
    out: Dict[str, float] = {}
    for k in keys:
        out[k] = float(after.get(k, 0.0)) - float(before.get(k, 0.0))
    return out


def compute_count_errors(rows: List[Tuple[str, int, int, int]]) -> Tuple[float, float]:
    if not rows:
        return 0.0, 0.0
    abs_errors = [abs(diff) for (_, _, _, diff) in rows]
    mae = float(stats.mean(abs_errors)) if abs_errors else 0.0
    ape = []
    for (_, gt, pr, _) in rows:
        if gt > 0:
            ape.append(abs((pr - gt) / gt) * 100.0)
    mape = float(stats.mean(ape)) if ape else 0.0
    return mae, mape


def main() -> None:
    root = os.path.abspath(os.getcwd())
    weights_path = os.path.join(root, "output", "train", "weights", "best.pt")
    data_yaml_path = os.path.join(root, "strawberry_dataset", "data.yaml")
    val_images = os.path.join(root, "strawberry_dataset", "images", "val")
    val_labels = os.path.join(root, "strawberry_dataset", "labels", "val")

    if not os.path.exists(weights_path) or not os.path.exists(data_yaml_path):
        os.makedirs(os.path.join(root, "output"), exist_ok=True)
        with open(os.path.join(root, "output", "report_metrics.md"), "w", encoding="utf-8") as f:
            f.write("### Autogenerated results\n\n")
            f.write("Weights or dataset not found. Run training notebook first.\n")
        return

    device = "cuda:0" if os.environ.get("CUDA_VISIBLE_DEVICES") or os.environ.get("NVIDIA_VISIBLE_DEVICES") else ("cuda:0" if _cuda_available() else "cpu")

    before_metrics = collect_pretrained_metrics(data_yaml_path, device=device)
    metrics = collect_val_metrics(weights_path, data_yaml_path, device=device)
    rows = build_count_table(weights_path, val_images, val_labels, device=device, max_rows=10, conf=0.5)
    deltas = compute_deltas(before_metrics, metrics)
    mae, mape = compute_count_errors(rows)

    out_path = os.path.join(root, "output", "report_metrics.md")
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("### Autogenerated results\n\n")
        f.write("Before (YOLOv11 pretrained) – validation metrics:\n\n")
        f.write("```json\n")
        f.write(json.dumps(before_metrics, indent=2))
        f.write("\n```\n\n")
        f.write("Validation metrics (YOLOv11 finetuned):\n\n")
        f.write("```json\n")
        f.write(json.dumps(metrics, indent=2))
        f.write("\n```\n\n")
        f.write("Deltas (after − before):\n\n")
        f.write("```json\n")
        f.write(json.dumps(deltas, indent=2))
        f.write("\n```\n\n")
        f.write("Count accuracy on sample validation images:\n\n")
        f.write("| filename | gt_count | yolo_count | diff |\n")
        f.write("|---|---:|---:|---:|\n")
        for name, gt, pr, diff in rows:
            f.write(f"| {name} | {gt} | {pr} | {diff} |\n")
        f.write("\nCount error summary (finetuned):\n\n")
        f.write(f"- MAE: {mae:.4f}\n")
        f.write(f"- MAPE: {mape:.2f}%\n")


def _cuda_available() -> bool:
    try:
        import torch  # type: ignore
        return torch.cuda.is_available()
    except Exception:
        return False


if __name__ == "__main__":
    main()
